// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'Vehicle.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Vehicle _$VehicleFromJson(Map<String, dynamic> json) {
  return Vehicle(
    json['originalOUId'] as int,
    json['joiningDate'] as String,
    json['ouDisplayName'] as String,
    json['vehicleCode'] as String,
    json['id'] as String,
    json['acquisitionDate'] as String,
    json['brandModel'] as String,
    json['brandModelText'] as String,
    json['creatorUserName'] as String,
    json['description'] as String,
    json['detailedOriginalOUId'] as int,
    json['detailedOUDisplayName'] as String,
    json['engineNumber'] as String,
    json['expectedroductionDate'] as String,
    json['frameNumber'] as String,
    json['introducer'] as String,
    json['introducerNames'] as String,
    json['lastModifierUserName'] as String,
    json['mainVehiclePlate'] as String,
    json['models'] as String,
    json['modelsText'] as String,
    json['ouFullName'] as String,
    json['ownerIDNumber'] as String,
    json['ownerName'] as String,
    json['ownerPhone'] as String,
    json['trailerFrameNumber'] as String,
    json['trailerNumber'] as String,
    json['vehicleBrand'] as String,
    json['vehicleBrandText'] as String,
    json['vehicleBusinessType'] as String,
    json['vehicleBusinessTypeText'] as String,
    json['vehicleGroup'] as String,
    json['vehicleGroupText'] as String,
    json['vehicleOwner'] as String,
    json['vehicleQualifications'] as String,
    json['vehicleQualificationsText'] as String,
    json['vehicleState'] as String,
    json['vehicleStateFlag'] as int,
    json['vehicleStateText'] as String,
    json['vehicleType'] as String,
    json['vehicleTypeText'] as String,
  );
}

Map<String, dynamic> _$VehicleToJson(Vehicle instance) => <String, dynamic>{
      'originalOUId': instance.originalOUId,
      'ouDisplayName': instance.ouDisplayName,
      'ouFullName': instance.ouFullName,
      'detailedOriginalOUId': instance.detailedOriginalOUId,
      'detailedOUDisplayName': instance.detailedOUDisplayName,
      'vehicleCode': instance.vehicleCode,
      'mainVehiclePlate': instance.mainVehiclePlate,
      'frameNumber': instance.frameNumber,
      'engineNumber': instance.engineNumber,
      'trailerNumber': instance.trailerNumber,
      'trailerFrameNumber': instance.trailerFrameNumber,
      'acquisitionDate': instance.acquisitionDate,
      'vehicleBrand': instance.vehicleBrand,
      'vehicleBrandText': instance.vehicleBrandText,
      'brandModel': instance.brandModel,
      'brandModelText': instance.brandModelText,
      'ownerIDNumber': instance.ownerIDNumber,
      'ownerName': instance.ownerName,
      'ownerPhone': instance.ownerPhone,
      'vehicleOwner': instance.vehicleOwner,
      'vehicleBusinessType': instance.vehicleBusinessType,
      'vehicleBusinessTypeText': instance.vehicleBusinessTypeText,
      'vehicleType': instance.vehicleType,
      'vehicleTypeText': instance.vehicleTypeText,
      'models': instance.models,
      'modelsText': instance.modelsText,
      'vehicleState': instance.vehicleState,
      'vehicleStateText': instance.vehicleStateText,
      'vehicleGroup': instance.vehicleGroup,
      'vehicleGroupText': instance.vehicleGroupText,
      'vehicleQualifications': instance.vehicleQualifications,
      'vehicleQualificationsText': instance.vehicleQualificationsText,
      'joiningDate': instance.joiningDate,
      'expectedroductionDate': instance.expectedroductionDate,
      'introducer': instance.introducer,
      'introducerNames': instance.introducerNames,
      'description': instance.description,
      'creatorUserName': instance.creatorUserName,
      'lastModifierUserName': instance.lastModifierUserName,
      'vehicleStateFlag': instance.vehicleStateFlag,
      'id': instance.id,
    };
