name: flutter_app123456
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.1+2
  json_annotation: ^2.0.0
  flutter_redux: ^0.5.3
  flutter_spinkit: ^3.1.0
  connectivity: ^0.4.2
  dio: ^2.1.0
  event_bus: ^1.0.3
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^3.0.3
  flutter_slidable: ^0.4.9
  web_socket_channel: ^1.0.9
  flutter_picker: ^1.1.0
  flutter_local_notifications: ^0.5.2
  animated_floatactionbuttons: ^0.1.0
  qr_flutter: ^2.0.0
  common_utils: ^1.1.1
  package_info: ^0.4.0+2
  pub_semver: ^1.4.2
  url_launcher: ^5.0.2
  banner_view: ^1.1.2
  intro_slider: ^2.2.5
  fluro: ^1.5.1
  flutter_datetime_picker: ^1.2.6
  sqflite: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  signalr_client: ^0.1.5


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  - lib/static/images/logo.jpg
  - lib/static/images/welcome.jpg
  - lib/static/images/welcome01.jpg
  - lib/static/images/welcome02.jpeg
  - lib/static/images/welcome03.jpeg
  - lib/static/images/welcome04.jpeg
  - lib/static/images/ic_arrow_right.png
  - lib/static/images/historybill.ico
  - lib/static/images/refuel.ico
  - lib/static/images/toll.ico
  - lib/static/images/cancelqueue.ico
  - lib/static/images/currentassgincustomer.ico
  - lib/static/images/freight.ico
  - lib/static/images/manualreceipt.ico
  - lib/static/images/maintenancefee.ico
  - lib/static/images/othercost.ico
  - lib/static/images/queuerefresh.ico
  - lib/static/images/user.ico
  - lib/static/images/userformy.ico
  - lib/static/images/userformy01.ico
  - lib/static/images/userformy02.ico
  - lib/static/images/leftdisplay.ico
  - lib/static/images/leftdisplay01.ico
  - lib/static/images/leftdisplay02.ico
  - lib/static/images/message.ico
  - lib/static/images/message32.ico
  - lib/static/images/login_ic.ico
  - lib/static/images/historybillsub.ico
  - lib/static/images/banner01.jpeg
  - lib/static/images/banner02.jpeg
  - assets/images/loginbackground.png
  - assets/images/loginbackgroundfull.jpg
  - assets/images/logo.png
  - assets/images/statelogo.png
  - assets/images/yixincloud.png
  - assets/images/banner.png
  - assets/images/cost.png
  - assets/images/current-customer.png
  - assets/images/freight.png
  - assets/images/history-bill.png
  - assets/images/maintenance.png
  - assets/images/refuel.png
  - assets/images/right.png
  - assets/images/toll.png
  - assets/images/welcome.png
  - assets/images/read.png
  - assets/images/readpressed.png
  - assets/images/unread.png
  - assets/images/unreadpressed.png
  - assets/images/setallread.png
  - assets/images/icon_msg.png
  - assets/images/messageunread.png
  - assets/images/nomore.png
  - assets/images/mybackground.png
  - assets/images/query.png
  - assets/images/form.png
  - assets/images/dairy.png
  fonts:
  - family: MyIcons
    fonts:
     - asset: assets/fonts/iconfont.ttf
  - family: MyFont
    fonts:
     - asset: assets/fonts/DroidSans.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
